[info] Loading settings from idea.sbt ...
[info] Loading global plugins from /home/girish/.sbt/1.0/plugins
[info] Updating ProjectRef(uri("file:/home/girish/.sbt/1.0/plugins/"), "global-plugins")...
[info] Done updating.
[info] Loading project definition from /home/girish/project
[info] Updating ProjectRef(uri("file:/home/girish/project/"), "girish-build")...
[info] Done updating.
[info] Set current project to girish (in build file:/home/girish/)
[success] Total time: 1 s, completed 20-Aug-2018, 2:28:57 PM
